# Commands to start on workspace startup
tasks:
  - init: go build -o grid-intensity
    command: |
      export PATH="$PATH:."
      chmod +x grid-intensity
      grid-intensity --help
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: ignore
