apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  gridIntensityLocation: {{ .Values.gridIntensity.location | quote }}
  gridIntensityProvider: {{ .Values.gridIntensity.provider | quote }}
  {{- if .Values.gridIntensity.region }}
  gridIntensityRegion: {{ .Values.gridIntensity.region | quote }}
  {{- end }}
