apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - exporter
        env:
        - name: GRID_INTENSITY_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}
              key: gridIntensityProvider
        - name: GRID_INTENSITY_LOCATION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}
              key: gridIntensityLocation
        - name: GRID_INTENSITY_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if .Values.gridIntensity.region }}
        - name: GRID_INTENSITY_REGION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}
              key: gridIntensityRegion
        {{- end }}
        {{- if .Values.electricityMap }}
        {{- if .Values.electricityMap.apiToken }}
        - name: ELECTRICITY_MAP_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: apiToken
        {{- end }}
        {{- end }}
        {{- if .Values.wattTime }}
        {{- if .Values.wattTime.apiUser }}
        - name: WATT_TIME_API_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: apiUser
        {{- end }}
        {{- if .Values.wattTime.apiPassword }}
        - name: WATT_TIME_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}
              key: apiPassword
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
