{{- if or (.Values.electricityMap) (.Values.wattTime) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
{{- if .Values.electricityMap }}
{{- if .Values.electricityMap.apiToken }}
  apiToken: {{ .Values.electricityMap.apiToken | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.wattTime }}
{{- if .Values.wattTime.apiUser }}
  apiUser: {{ .Values.wattTime.apiUser | b64enc | quote }}
{{- end }}
{{- if .Values.wattTime.apiPassword }}
  apiPassword: {{ .Values.wattTime.apiPassword | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
