apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
{{ if .Values.gridIntensity.apiToken }}
  apiToken: {{ .Values.gridIntensity.apiToken | b64enc | quote }}
{{ end }}
{{ if .Values.wattTime.apiUser }}
  apiUser: {{ .Values.wattTime.apiUser | b64enc | quote }}
{{ end }}
{{ if .Values.wattTime.apiPassword }}
  apiPassword: {{ .Values.wattTime.apiPassword | b64enc | quote }}
{{ end }}
