# This is the default provider with the Ember 2021 dataset.
gridIntensity:
  provider: Ember
  region: GBR

image:
  repository: thegreenwebfoundation/grid-intensity
  tag: latest
  pullPolicy: IfNotPresent

# This provider doesn't require an API key but it only
# supports the UK region.
#
# gridIntensity:
#   provider: CarbonIntensityOrgUK
#   region: UK

# ElectricityMap provider supports multiple countries but you will need to set
# an API key in electricityMap.apiToken 
#
# gridIntensity:
#   provider: ElectricityMap
#   region: IN-KA

# WattTime provider supports multiple countries but you will need to set an API
# user in wattTime.apiUser and wattTime.apiPassword
#
# gridIntensity:
#   provider: WattTime
#   region: CAISO_NORTH

# Get API token from https://electricitymaps.com/
#
# electricityMap:
#   apiToken: your-api-key

# To register an API user see https://www.watttime.org/api-documentation/#authentication
#
# wattTime:
#   apiUser: your-api-user
#   apiPassword: your-api-password
