name: docker-integration-test
on: [pull_request, push]
jobs:
  docker-integration-test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
      - 
        name: Go build
        run: CGO_ENABLED=0 GOOS=linux go build -o grid-intensity .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: thegreenwebfoundation/grid-intensity:integration-test
      -
        name: Docker run
        run: docker run -d -e GRID_INTENSITY_LOCATION=GBR -p 8000:8000 thegreenwebfoundation/grid-intensity:integration-test exporter
      - 
        name: Run integration test
        run: go test -v -tags=dockerrequired ./integration/test/exporter
