on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Get token
        id: get_token
        uses: getsentry/action-github-app-token@main
        with:
          app_id: ${{ secrets.HOMEBREW_TAP_GITHUB_APP_ID }}
          private_key: ${{ secrets.HOMEBREW_TAP_GITHUB_APP_PEM }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
