name: go-unit-test
on: [push]
jobs:
  go-unit-test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Go test
        run: go test ./...
