name: go-unit-test
on: [push]
jobs:
  go-unit-test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
      - 
        name: Go test
        run: go test ./...
